export default [
  {
      id: 1,
      postedOn: '2023-10-28',
      title: 'iOS Developer',
      company: 'Apple',
      type: 'Full Time',
      experience: 'Mid Level',
      location: 'Remote',
      skills: ["SwiftUI", "UiKit", "Core Data"],
      job_link: "https://www.apple.com/careers/in/",
  },
  {
      id: 2,
      postedOn: '2023-10-24',
      title: "Frontend Developer",
      type: "Full time",
      location: "In-office",
      experience: "Fresher",
      company: "Amazon",
      skills: ["Javascript", "Nextjs", "Tailwind CSS"],
      job_link: "https://www.amazon.jobs/en/",
  },
  {
      id: 3,
      postedOn: '2023-11-02',
      title: "Android Developer",
      type: "Part time",
      location: "Remote",
      experience: "Senior Level",
      company: "Facebook",
      skills: ["Kotlin", "MVVM"],
      job_link: "https://facebook.com/careers",
  },
  {
      id: 4,
      postedOn: '2023-11-01',
      title: "Developer Advocate",
      type: "Contract",
      location: "Hybrid",
      experience: "Junior Level",
      company: "Netflix",
      skills: ["web3", "Content Creation", "Community"],
      job_link: "https://jobs.netflix.com/",
  },
  {
      id: 5,
      postedOn: '2023-11-05',
      title: "Full Stack Developer",
      type: "Full Time",
      location: "Remote",
      experience: "Mid Level",
      company: "Google",
      skills: ["React.js", "Node.js", "MongoDB"],
      job_link: "https://careers.google.com/",
  },
  {
      id: 6,
      postedOn: '2023-10-30',
      title: "Data Scientist",
      type: "Part Time",
      location: "In-office",
      experience: "Senior Level",
      company: "Microsoft",
      skills: ["Python", "Machine Learning", "TensorFlow"],
      job_link: "https://careers.microsoft.com/",
  },
  {
      id: 7,
      postedOn: '2023-11-03',
      title: "Backend Developer",
      type: "Full Time",
      location: "Remote",
      experience: "Mid Level",
      company: "Uber",
      skills: ["Node.js", "Express", "MySQL"],
      job_link: "https://careers.uber.com/",
  },
  {
      id: 8,
      postedOn: '2023-11-04',
      title: "DevOps Engineer",
      type: "Contract",
      location: "Hybrid",
      experience: "Mid Level",
      company: "Spotify",
      skills: ["AWS", "Docker", "Kubernetes"],
      job_link: "https://www.spotifyjobs.com/",
  },
  {
      id: 9,
      postedOn: '2023-10-29',
      title: "UI/UX Designer",
      type: "Full Time",
      location: "In-office",
      experience: "Junior Level",
      company: "Tesla",
      skills: ["Figma", "Adobe XD", "Wireframing"],
      job_link: "https://www.tesla.com/careers",
  },
  {
      id: 10,
      postedOn: '2023-11-06',
      title: "Blockchain Developer",
      type: "Full Time",
      location: "Remote",
      experience: "Senior Level",
      company: "Coinbase",
      skills: ["Solidity", "Ethereum", "Smart Contracts"],
      job_link: "https://www.coinbase.com/careers",
  },
  {
      id: 11,
      postedOn: '2023-10-27',
      title: "Cloud Engineer",
      type: "Part Time",
      location: "Remote",
      experience: "Mid Level",
      company: "Oracle",
      skills: ["Azure", "Google Cloud", "AWS"],
      job_link: "https://careers.oracle.com/",
  },
  {
      id: 12,
      postedOn: '2023-11-08',
      title: "Security Analyst",
      type: "Full Time",
      location: "In-office",
      experience: "Junior Level",
      company: "Zoom",
      skills: ["Cybersecurity", "Penetration Testing", "Firewalls"],
      job_link: "https://careers.zoom.us/",
  },
  {
      id: 13,
      postedOn: '2023-10-31',
      title: "AI Engineer",
      type: "Full Time",
      location: "Remote",
      experience: "Senior Level",
      company: "OpenAI",
      skills: ["Python", "Deep Learning", "NLP"],
      job_link: "https://careers.openai.com/",
  },
];
